apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: gm43kae3s-nodejs 
  janus-idp.io/tekton: gm43kae3s-nodejs
  backstage.io/kubernetes-id: gm43kae3s-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gm43kae3s-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml